services:
  - type: web
    name: agenda-eventos-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
